<?php

namespace App\Mcp\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Tool;

class GetBookings extends Tool
{
    /**
     * The tool's description.
     */
    protected string $name = "Get Bookings";

    protected string $title = "Get Bookings Tool";

    protected string $description = "This tool retrieves a list of bookings.";

    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
        //

        return Response::text('The content generated by the tool.');
    }

    /**
     * Get the tool's input schema.
     *
     * @return array<string, \Illuminate\Contracts\JsonSchema\JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            //
        ];
    }
}
